### ISSUE TITLE
Linter errors

### ISSUE THREAD

**Issue by carreraprogrammer** [carreraprogrammer/school-library#7]
Hello @Metaverse-Nabeel 👋, we have some linter errors that we need to fix, please take a look and tell me if you find a solution

![Captura desde 2023-06-27 18-56-21](https://github.com/carreraprogrammer/school-library/assets/109081622/2485869b-f99a-4d4f-9ec1-8c5ee675b9c8)

**Comment by Metaverse-Nabeel** [comment]
Corrected all the linter errors. I shall try to complete the task of adding local storage.
